### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by damikun** [udecode/plate-playground#3]
I have issue to make it run after installing i get some errors for peer deps.. I'm using pnpm as was in Readme but also tried yarn cannot install and build properly... 

![image](https://github.com/udecode/plate-playground-template/assets/54806834/35e77209-056d-4ab6-8bc4-543d18299ed1)

slate-hyperscript seem to be issue... What Noe you use ?

**Comment by damikun** [comment]
Ok solution there is missing `.npmrc` file with content `auto-install-peers=true`

**Comment by zbeyens** [comment]
Thanks for the issue. Added `slate-hyperscript` to deps.

**Comment by damikun** [comment]
Pls @zbeyens  also check for this 

![image](https://github.com/udecode/plate-playground-template/assets/54806834/cbd1faaa-66fd-4cc1-a14c-2e3579ea82ac)

**Comment by zbeyens** [comment]
Fixed: 
```json
"pnpm": {
    "peerDependencyRules": {
      "allowAny": ["react", "react-dom"],
      "ignoreMissing": ["scheduler"]
    }
  }
```

**Comment by damikun** [comment]
I`m still facing more issues when i wanna run locally..
- The default nextjs does not sets experimental to app dir...  (config is empty)

```
const nextConfig = {
  experimental: {
    appDir: true,
  },
}
```

And after setting up still not able to run locally after dev server starts isn`t there some missing config ?

**Comment by zbeyens** [comment]
I think it's an issue on your side. It works flawlessly on a new clone repo: `pnpm install` then `pnpm dev`.

**Comment by damikun** [comment]
Ahh i was using template by  `pnpm create next-app -e https://github.com/udecode/plate-playground-template`  from ReadMe

**Comment by damikun** [comment]
Can confirm that using `pnpm install` and  `pnpm dev` it works.. But seems template way not..

**Comment by zbeyens** [comment]
Updated the README
